//! Repository automation shared by the `cargo xtask` command and tests.

use std::{fs, path::Path};

use anyhow::{Context, Result, bail};
use schemars::{JsonSchema, schema_for};
use serde_json::Value;
use weregopher_domain::{
    BuildFingerprint, CallContext, CandidateProfile, CertificationClass, EffectiveSecurityPosture,
    FrameHeader, ProtocolLimits, PublicationStatus, TrustMode, WireValue,
};
use weregopher_fingerprint::PackageTreeManifest;

/// Canonical generated schema filenames in deterministic order.
pub const SCHEMA_FILENAMES: [&str; 11] = [
    "build-fingerprint.schema.json",
    "call-context.schema.json",
    "candidate-profile.schema.json",
    "certification-class.schema.json",
    "effective-security-posture.schema.json",
    "frame-header.schema.json",
    "package-tree-manifest.schema.json",
    "protocol-limits.schema.json",
    "publication-status.schema.json",
    "trust-mode.schema.json",
    "wire-value.schema.json",
];

/// Writes every canonical JSON Schema into `output_directory`.
///
/// # Errors
///
/// Returns an error when schema serialization or an output-directory write fails.
pub fn generate_schemas(output_directory: &Path) -> Result<()> {
    fs::create_dir_all(output_directory).with_context(|| {
        format!(
            "failed to create schema directory {}",
            output_directory.display()
        )
    })?;

    for (filename, bytes) in schema_documents()? {
        let path = output_directory.join(filename);
        fs::write(&path, bytes)
            .with_context(|| format!("failed to write generated schema {}", path.display()))?;
    }
    Ok(())
}

/// Verifies that checked-in schemas exactly match canonical generation.
///
/// # Errors
///
/// Returns an error when a schema is missing, unreadable, or differs from its
/// canonical generated bytes.
pub fn check_schemas(output_directory: &Path) -> Result<()> {
    for (filename, expected) in schema_documents()? {
        let path = output_directory.join(filename);
        let actual = fs::read(&path)
            .with_context(|| format!("generated schema is missing: {}", path.display()))?;
        if actual != expected {
            bail!(
                "generated schema is stale: {}; run `cargo xtask schema`",
                path.display()
            );
        }
    }
    Ok(())
}

/// Runs one repository automation command relative to `repository_root`.
///
/// # Errors
///
/// Returns an error when arguments do not name a supported command or the
/// selected schema operation fails.
pub fn run<I, S>(arguments: I, repository_root: &Path) -> Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let arguments: Vec<String> = arguments
        .into_iter()
        .map(|argument| argument.as_ref().to_owned())
        .collect();
    let schema_directory = repository_root.join("schemas");

    match arguments.as_slice() {
        [command] if command == "schema" => generate_schemas(&schema_directory),
        [command, flag] if command == "schema" && flag == "--check" => {
            check_schemas(&schema_directory)
        }
        _ => bail!("usage: cargo xtask schema [--check]"),
    }
}

fn schema_documents() -> Result<Vec<(&'static str, Vec<u8>)>> {
    Ok(vec![
        schema_document::<BuildFingerprint>(SCHEMA_FILENAMES[0])?,
        schema_document::<CallContext>(SCHEMA_FILENAMES[1])?,
        schema_document::<CandidateProfile>(SCHEMA_FILENAMES[2])?,
        schema_document::<CertificationClass>(SCHEMA_FILENAMES[3])?,
        schema_document::<EffectiveSecurityPosture>(SCHEMA_FILENAMES[4])?,
        schema_document::<FrameHeader>(SCHEMA_FILENAMES[5])?,
        schema_document::<PackageTreeManifest>(SCHEMA_FILENAMES[6])?,
        schema_document::<ProtocolLimits>(SCHEMA_FILENAMES[7])?,
        schema_document::<PublicationStatus>(SCHEMA_FILENAMES[8])?,
        schema_document::<TrustMode>(SCHEMA_FILENAMES[9])?,
        schema_document::<WireValue>(SCHEMA_FILENAMES[10])?,
    ])
}

fn schema_document<T: JsonSchema>(filename: &'static str) -> Result<(&'static str, Vec<u8>)> {
    let mut document = serde_json::to_value(schema_for!(T))?;
    normalize_schema_meta(&mut document);
    let mut bytes = serde_json::to_vec_pretty(&document)?;
    bytes.push(b'\n');
    Ok((filename, bytes))
}

fn normalize_schema_meta(document: &mut Value) {
    if let Value::Object(object) = document {
        object.insert(
            "$schema".to_owned(),
            Value::String("https://json-schema.org/draft/2020-12/schema".to_owned()),
        );
    }
    add_explicit_integer_bounds(document);
}

fn add_explicit_integer_bounds(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let format = object
                .get("format")
                .and_then(Value::as_str)
                .map(str::to_owned);
            if let Some((minimum, maximum)) = format.as_deref().and_then(integer_bounds) {
                object.entry("minimum").or_insert(minimum);
                object.entry("maximum").or_insert(maximum);
            }
            for child in object.values_mut() {
                add_explicit_integer_bounds(child);
            }
        }
        Value::Array(values) => {
            for child in values {
                add_explicit_integer_bounds(child);
            }
        }
        _ => {}
    }
}

fn integer_bounds(format: &str) -> Option<(Value, Value)> {
    match format {
        "uint8" => Some((Value::from(0), Value::from(u8::MAX))),
        "uint16" => Some((Value::from(0), Value::from(u16::MAX))),
        "uint32" => Some((Value::from(0), Value::from(u32::MAX))),
        "uint64" => Some((Value::from(0), Value::from(u64::MAX))),
        "int8" => Some((Value::from(i8::MIN), Value::from(i8::MAX))),
        "int16" => Some((Value::from(i16::MIN), Value::from(i16::MAX))),
        "int32" => Some((Value::from(i32::MIN), Value::from(i32::MAX))),
        "int64" => Some((Value::from(i64::MIN), Value::from(i64::MAX))),
        _ => None,
    }
}
