//! Repository automation shared by the `cargo xtask` command and tests.

use std::{fs, path::Path};

use anyhow::{Context, Result, bail};
use schemars::{JsonSchema, schema_for};
use serde_json::{Value, json};
use weregopher_domain::{
    AdapterExecutionAuthority, AdapterTransformAuthority, BuildFingerprint, CallContext,
    CandidateInstallationEvidence, CandidateProfile, CertificationClass, CertificationEvidence,
    CertificationProfile, CompatibilityAnalysis, EffectiveSecurityPosture,
    ExecutionResolutionEvidence, ExecutionTargetContract, FrameHeader, GeneratedExecutionOverlay,
    GeneratedTransformOverlay, ProtocolLimits, PublicationStatus, TrustMode, WireValue,
};
use weregopher_fingerprint::PackageTreeManifest;

/// Canonical generated schema filenames in deterministic order.
pub const SCHEMA_FILENAMES: [&str; 21] = [
    "adapter-execution-authority.schema.json",
    "adapter-transform-authority.schema.json",
    "build-fingerprint.schema.json",
    "call-context.schema.json",
    "candidate-installation-evidence.schema.json",
    "candidate-profile.schema.json",
    "certification-class.schema.json",
    "certification-evidence.schema.json",
    "certification-profile.schema.json",
    "compatibility-analysis.schema.json",
    "effective-security-posture.schema.json",
    "execution-resolution-evidence.schema.json",
    "execution-target-contract.schema.json",
    "frame-header.schema.json",
    "generated-execution-overlay.schema.json",
    "generated-transform-overlay.schema.json",
    "package-tree-manifest.schema.json",
    "protocol-limits.schema.json",
    "publication-status.schema.json",
    "trust-mode.schema.json",
    "wire-value.schema.json",
];

/// Writes every canonical JSON Schema into `output_directory`.
///
/// # Errors
///
/// Returns an error when schema serialization or an output-directory write fails.
pub fn generate_schemas(output_directory: &Path) -> Result<()> {
    fs::create_dir_all(output_directory).with_context(|| {
        format!(
            "failed to create schema directory {}",
            output_directory.display()
        )
    })?;

    for (filename, bytes) in schema_documents()? {
        let path = output_directory.join(filename);
        fs::write(&path, bytes)
            .with_context(|| format!("failed to write generated schema {}", path.display()))?;
    }
    Ok(())
}

/// Verifies that checked-in schemas exactly match canonical generation.
///
/// # Errors
///
/// Returns an error when a schema is missing, unreadable, or differs from its
/// canonical generated bytes.
pub fn check_schemas(output_directory: &Path) -> Result<()> {
    for (filename, expected) in schema_documents()? {
        let path = output_directory.join(filename);
        let actual = fs::read(&path)
            .with_context(|| format!("generated schema is missing: {}", path.display()))?;
        if actual != expected {
            bail!(
                "generated schema is stale: {}; run `cargo xtask schema`",
                path.display()
            );
        }
    }
    Ok(())
}

/// Runs one repository automation command relative to `repository_root`.
///
/// # Errors
///
/// Returns an error when arguments do not name a supported command or the
/// selected schema operation fails.
pub fn run<I, S>(arguments: I, repository_root: &Path) -> Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let arguments: Vec<String> = arguments
        .into_iter()
        .map(|argument| argument.as_ref().to_owned())
        .collect();
    let schema_directory = repository_root.join("schemas");

    match arguments.as_slice() {
        [command] if command == "schema" => generate_schemas(&schema_directory),
        [command, flag] if command == "schema" && flag == "--check" => {
            check_schemas(&schema_directory)
        }
        _ => bail!("usage: cargo xtask schema [--check]"),
    }
}

fn schema_documents() -> Result<Vec<(&'static str, Vec<u8>)>> {
    Ok(vec![
        schema_document::<AdapterExecutionAuthority>(SCHEMA_FILENAMES[0])?,
        schema_document::<AdapterTransformAuthority>(SCHEMA_FILENAMES[1])?,
        schema_document::<BuildFingerprint>(SCHEMA_FILENAMES[2])?,
        schema_document::<CallContext>(SCHEMA_FILENAMES[3])?,
        schema_document::<CandidateInstallationEvidence>(SCHEMA_FILENAMES[4])?,
        schema_document::<CandidateProfile>(SCHEMA_FILENAMES[5])?,
        schema_document::<CertificationClass>(SCHEMA_FILENAMES[6])?,
        schema_document::<CertificationEvidence>(SCHEMA_FILENAMES[7])?,
        schema_document::<CertificationProfile>(SCHEMA_FILENAMES[8])?,
        schema_document::<CompatibilityAnalysis>(SCHEMA_FILENAMES[9])?,
        schema_document::<EffectiveSecurityPosture>(SCHEMA_FILENAMES[10])?,
        schema_document::<ExecutionResolutionEvidence>(SCHEMA_FILENAMES[11])?,
        schema_document::<ExecutionTargetContract>(SCHEMA_FILENAMES[12])?,
        schema_document::<FrameHeader>(SCHEMA_FILENAMES[13])?,
        schema_document::<GeneratedExecutionOverlay>(SCHEMA_FILENAMES[14])?,
        schema_document::<GeneratedTransformOverlay>(SCHEMA_FILENAMES[15])?,
        schema_document::<PackageTreeManifest>(SCHEMA_FILENAMES[16])?,
        schema_document::<ProtocolLimits>(SCHEMA_FILENAMES[17])?,
        schema_document::<PublicationStatus>(SCHEMA_FILENAMES[18])?,
        schema_document::<TrustMode>(SCHEMA_FILENAMES[19])?,
        schema_document::<WireValue>(SCHEMA_FILENAMES[20])?,
    ])
}

fn schema_document<T: JsonSchema>(filename: &'static str) -> Result<(&'static str, Vec<u8>)> {
    let mut document = serde_json::to_value(schema_for!(T))?;
    normalize_schema_meta(&mut document, filename)?;
    let mut bytes = serde_json::to_vec_pretty(&document)?;
    bytes.push(b'\n');
    Ok((filename, bytes))
}

fn normalize_schema_meta(document: &mut Value, filename: &str) -> Result<()> {
    if let Value::Object(object) = document {
        object.insert(
            "$schema".to_owned(),
            Value::String("https://json-schema.org/draft/2020-12/schema".to_owned()),
        );
    }
    add_explicit_integer_bounds(document);
    if filename == "certification-evidence.schema.json" {
        annotate_certification_evidence(document)?;
    }
    if filename == "certification-profile.schema.json" {
        annotate_certification_profile(document)?;
    }
    if filename == "compatibility-analysis.schema.json" {
        require_evidence_for_resolved_compatibility_assessments(document)?;
    }
    match filename {
        "execution-target-contract.schema.json" => annotate_execution_target_limits(document)?,
        "execution-resolution-evidence.schema.json" => {
            annotate_execution_resolution_limits(document)?;
        }
        _ => {}
    }
    Ok(())
}

fn annotate_certification_evidence(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("certification evidence schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_DOCUMENT_BYTES),
    );
    let assessment = document
        .pointer_mut("/$defs/CertificationCheckAssessment")
        .and_then(Value::as_object_mut)
        .context("certification schema is missing its check-assessment definition")?;
    assessment.insert(
        "allOf".to_owned(),
        json!([{
            "if": {
                "properties": {
                    "status": { "const": "not_run" }
                },
                "required": ["status"]
            },
            "then": {
                "properties": {
                    "evidence": { "maxItems": 0 }
                }
            },
            "else": {
                "properties": {
                    "evidence": { "minItems": 1 }
                }
            }
        }]),
    );
    Ok(())
}

fn annotate_certification_profile(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("certification profile schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_PROFILE_DOCUMENT_BYTES),
    );
    Ok(())
}

fn annotate_execution_target_limits(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("execution target schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_EXECUTION_TARGET_DOCUMENT_BYTES),
    );
    let arguments = document
        .pointer_mut("/$defs/ExecutionLaunchPolicy/properties/arguments")
        .and_then(Value::as_object_mut)
        .context("execution target schema is missing launch arguments")?;
    arguments.insert(
        "x-weregopher-maxAggregateUtf8Bytes".to_owned(),
        json!(weregopher_domain::MAX_EXECUTION_ARGUMENT_AGGREGATE_BYTES),
    );
    Ok(())
}

fn annotate_execution_resolution_limits(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("execution resolution schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_EXECUTION_RESOLUTION_DOCUMENT_BYTES),
    );
    root.insert(
        "x-weregopher-managedLocatorDigestEqualsExecutableDigest".to_owned(),
        Value::Bool(true),
    );
    Ok(())
}

fn require_evidence_for_resolved_compatibility_assessments(document: &mut Value) -> Result<()> {
    let assessment = document
        .pointer_mut("/$defs/DimensionAssessment")
        .and_then(Value::as_object_mut)
        .context("compatibility schema is missing its dimension-assessment definition")?;
    assessment.insert(
        "allOf".to_owned(),
        json!([{
            "if": {
                "properties": {
                    "status": {
                        "enum": ["satisfied", "unsatisfied", "not_applicable"]
                    }
                },
                "required": ["status"]
            },
            "then": {
                "properties": {
                    "evidence": {
                        "minItems": 1
                    }
                }
            }
        }]),
    );
    Ok(())
}

fn add_explicit_integer_bounds(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let format = object
                .get("format")
                .and_then(Value::as_str)
                .map(str::to_owned);
            if let Some((minimum, maximum)) = format.as_deref().and_then(integer_bounds) {
                object.entry("minimum").or_insert(minimum);
                object.entry("maximum").or_insert(maximum);
            }
            for child in object.values_mut() {
                add_explicit_integer_bounds(child);
            }
        }
        Value::Array(values) => {
            for child in values {
                add_explicit_integer_bounds(child);
            }
        }
        _ => {}
    }
}

fn integer_bounds(format: &str) -> Option<(Value, Value)> {
    match format {
        "uint8" => Some((Value::from(0), Value::from(u8::MAX))),
        "uint16" => Some((Value::from(0), Value::from(u16::MAX))),
        "uint32" => Some((Value::from(0), Value::from(u32::MAX))),
        "uint64" => Some((Value::from(0), Value::from(u64::MAX))),
        "int8" => Some((Value::from(i8::MIN), Value::from(i8::MAX))),
        "int16" => Some((Value::from(i16::MIN), Value::from(i16::MAX))),
        "int32" => Some((Value::from(i32::MIN), Value::from(i32::MAX))),
        "int64" => Some((Value::from(i64::MIN), Value::from(i64::MAX))),
        _ => None,
    }
}
