//! Repository automation shared by the `cargo xtask` command and tests.

use std::{fs, path::Path};

use anyhow::{Context, Result, bail};
use schemars::{JsonSchema, schema_for};
use serde_json::{Value, json};
use weregopher_adapter_discord::DiscordSmokeCertificationReport;
use weregopher_domain::{
    AdapterExecutionAuthority, AdapterTransformAuthority, AppServerProbeReport, BuildFingerprint,
    CallContext, CandidateInstallationEvidence, CandidateProfile, CertificationClass,
    CertificationEvidence, CertificationProfile, CertificationRunnerComponentDescriptor,
    CertificationRunnerIdentity, CompatibilityAnalysis, DisposableCertificationScenario,
    DisposableCertificationScenarioReport, EffectiveSecurityPosture, ExecutionResolutionEvidence,
    ExecutionTargetContract, FrameHeader, G2FeasibilityReport, GeneratedExecutionOverlay,
    GeneratedTransformOverlay, HeartbeatPolicy, LocalCertificationLedgerRecord,
    LocalCertificationRunAttestation, OpenAiPackageInventory, PreloadBridgeProbeReport,
    ProtocolFeatures, ProtocolLimits, ProtocolReject, ProtocolVersion, ProtocolVersionRange,
    PublicationStatus, RendererBridgeInvocation, RendererBridgeReply, RendererEnvelope,
    RuntimeBackendIdentity, RuntimeCall, RuntimeCallError, RuntimeCallResult, RuntimeCancel,
    RuntimeEvent, RuntimeHello, RuntimeShutdown, RuntimeStreamData, RuntimeStreamOpen,
    RuntimeStreamWindow, RuntimeWelcome, TrustMode, WireValue,
};
use weregopher_fingerprint::PackageTreeManifest;

/// Canonical generated schema filenames in deterministic order.
pub const SCHEMA_FILENAMES: [&str; 52] = [
    "adapter-execution-authority.schema.json",
    "adapter-transform-authority.schema.json",
    "app-server-probe-report.schema.json",
    "build-fingerprint.schema.json",
    "call-context.schema.json",
    "candidate-installation-evidence.schema.json",
    "candidate-profile.schema.json",
    "certification-class.schema.json",
    "certification-evidence.schema.json",
    "certification-profile.schema.json",
    "certification-runner-component-descriptor.schema.json",
    "certification-runner-identity.schema.json",
    "compatibility-analysis.schema.json",
    "disposable-certification-scenario-report.schema.json",
    "disposable-certification-scenario.schema.json",
    "discord-smoke-certification-report.schema.json",
    "effective-security-posture.schema.json",
    "execution-resolution-evidence.schema.json",
    "execution-target-contract.schema.json",
    "frame-header.schema.json",
    "g2-feasibility-report.schema.json",
    "generated-execution-overlay.schema.json",
    "generated-transform-overlay.schema.json",
    "heartbeat-policy.schema.json",
    "local-certification-ledger-record.schema.json",
    "local-certification-run-attestation.schema.json",
    "openai-package-inventory.schema.json",
    "package-tree-manifest.schema.json",
    "preload-bridge-probe-report.schema.json",
    "protocol-features.schema.json",
    "protocol-limits.schema.json",
    "protocol-reject.schema.json",
    "protocol-version.schema.json",
    "protocol-version-range.schema.json",
    "publication-status.schema.json",
    "renderer-bridge-invocation.schema.json",
    "renderer-bridge-reply.schema.json",
    "renderer-envelope.schema.json",
    "runtime-backend-identity.schema.json",
    "runtime-call.schema.json",
    "runtime-call-error.schema.json",
    "runtime-call-result.schema.json",
    "runtime-cancel.schema.json",
    "runtime-event.schema.json",
    "runtime-hello.schema.json",
    "runtime-shutdown.schema.json",
    "runtime-stream-data.schema.json",
    "runtime-stream-open.schema.json",
    "runtime-stream-window.schema.json",
    "runtime-welcome.schema.json",
    "trust-mode.schema.json",
    "wire-value.schema.json",
];

/// Writes every canonical JSON Schema into `output_directory`.
///
/// # Errors
///
/// Returns an error when schema serialization or an output-directory write fails.
pub fn generate_schemas(output_directory: &Path) -> Result<()> {
    fs::create_dir_all(output_directory).with_context(|| {
        format!(
            "failed to create schema directory {}",
            output_directory.display()
        )
    })?;

    for (filename, bytes) in schema_documents()? {
        let path = output_directory.join(filename);
        fs::write(&path, bytes)
            .with_context(|| format!("failed to write generated schema {}", path.display()))?;
    }
    Ok(())
}

/// Verifies that checked-in schemas exactly match canonical generation.
///
/// # Errors
///
/// Returns an error when a schema is missing, unreadable, or differs from its
/// canonical generated bytes.
pub fn check_schemas(output_directory: &Path) -> Result<()> {
    for (filename, expected) in schema_documents()? {
        let path = output_directory.join(filename);
        let actual = fs::read(&path)
            .with_context(|| format!("generated schema is missing: {}", path.display()))?;
        if actual != expected {
            bail!(
                "generated schema is stale: {}; run `cargo xtask schema`",
                path.display()
            );
        }
    }
    Ok(())
}

/// Runs one repository automation command relative to `repository_root`.
///
/// # Errors
///
/// Returns an error when arguments do not name a supported command or the
/// selected schema operation fails.
pub fn run<I, S>(arguments: I, repository_root: &Path) -> Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let arguments: Vec<String> = arguments
        .into_iter()
        .map(|argument| argument.as_ref().to_owned())
        .collect();
    let schema_directory = repository_root.join("schemas");

    match arguments.as_slice() {
        [command] if command == "schema" => generate_schemas(&schema_directory),
        [command, flag] if command == "schema" && flag == "--check" => {
            check_schemas(&schema_directory)
        }
        _ => bail!("usage: cargo xtask schema [--check]"),
    }
}

fn schema_documents() -> Result<Vec<(&'static str, Vec<u8>)>> {
    Ok(vec![
        schema_document::<AdapterExecutionAuthority>(SCHEMA_FILENAMES[0])?,
        schema_document::<AdapterTransformAuthority>(SCHEMA_FILENAMES[1])?,
        schema_document::<AppServerProbeReport>(SCHEMA_FILENAMES[2])?,
        schema_document::<BuildFingerprint>(SCHEMA_FILENAMES[3])?,
        schema_document::<CallContext>(SCHEMA_FILENAMES[4])?,
        schema_document::<CandidateInstallationEvidence>(SCHEMA_FILENAMES[5])?,
        schema_document::<CandidateProfile>(SCHEMA_FILENAMES[6])?,
        schema_document::<CertificationClass>(SCHEMA_FILENAMES[7])?,
        schema_document::<CertificationEvidence>(SCHEMA_FILENAMES[8])?,
        schema_document::<CertificationProfile>(SCHEMA_FILENAMES[9])?,
        schema_document::<CertificationRunnerComponentDescriptor>(SCHEMA_FILENAMES[10])?,
        schema_document::<CertificationRunnerIdentity>(SCHEMA_FILENAMES[11])?,
        schema_document::<CompatibilityAnalysis>(SCHEMA_FILENAMES[12])?,
        schema_document::<DisposableCertificationScenarioReport>(SCHEMA_FILENAMES[13])?,
        schema_document::<DisposableCertificationScenario>(SCHEMA_FILENAMES[14])?,
        schema_document::<DiscordSmokeCertificationReport>(SCHEMA_FILENAMES[15])?,
        schema_document::<EffectiveSecurityPosture>(SCHEMA_FILENAMES[16])?,
        schema_document::<ExecutionResolutionEvidence>(SCHEMA_FILENAMES[17])?,
        schema_document::<ExecutionTargetContract>(SCHEMA_FILENAMES[18])?,
        schema_document::<FrameHeader>(SCHEMA_FILENAMES[19])?,
        schema_document::<G2FeasibilityReport>(SCHEMA_FILENAMES[20])?,
        schema_document::<GeneratedExecutionOverlay>(SCHEMA_FILENAMES[21])?,
        schema_document::<GeneratedTransformOverlay>(SCHEMA_FILENAMES[22])?,
        schema_document::<HeartbeatPolicy>(SCHEMA_FILENAMES[23])?,
        schema_document::<LocalCertificationLedgerRecord>(SCHEMA_FILENAMES[24])?,
        schema_document::<LocalCertificationRunAttestation>(SCHEMA_FILENAMES[25])?,
        schema_document::<OpenAiPackageInventory>(SCHEMA_FILENAMES[26])?,
        schema_document::<PackageTreeManifest>(SCHEMA_FILENAMES[27])?,
        schema_document::<PreloadBridgeProbeReport>(SCHEMA_FILENAMES[28])?,
        schema_document::<ProtocolFeatures>(SCHEMA_FILENAMES[29])?,
        schema_document::<ProtocolLimits>(SCHEMA_FILENAMES[30])?,
        schema_document::<ProtocolReject>(SCHEMA_FILENAMES[31])?,
        schema_document::<ProtocolVersion>(SCHEMA_FILENAMES[32])?,
        schema_document::<ProtocolVersionRange>(SCHEMA_FILENAMES[33])?,
        schema_document::<PublicationStatus>(SCHEMA_FILENAMES[34])?,
        schema_document::<RendererBridgeInvocation>(SCHEMA_FILENAMES[35])?,
        schema_document::<RendererBridgeReply>(SCHEMA_FILENAMES[36])?,
        schema_document::<RendererEnvelope>(SCHEMA_FILENAMES[37])?,
        schema_document::<RuntimeBackendIdentity>(SCHEMA_FILENAMES[38])?,
        schema_document::<RuntimeCall>(SCHEMA_FILENAMES[39])?,
        schema_document::<RuntimeCallError>(SCHEMA_FILENAMES[40])?,
        schema_document::<RuntimeCallResult>(SCHEMA_FILENAMES[41])?,
        schema_document::<RuntimeCancel>(SCHEMA_FILENAMES[42])?,
        schema_document::<RuntimeEvent>(SCHEMA_FILENAMES[43])?,
        schema_document::<RuntimeHello>(SCHEMA_FILENAMES[44])?,
        schema_document::<RuntimeShutdown>(SCHEMA_FILENAMES[45])?,
        schema_document::<RuntimeStreamData>(SCHEMA_FILENAMES[46])?,
        schema_document::<RuntimeStreamOpen>(SCHEMA_FILENAMES[47])?,
        schema_document::<RuntimeStreamWindow>(SCHEMA_FILENAMES[48])?,
        schema_document::<RuntimeWelcome>(SCHEMA_FILENAMES[49])?,
        schema_document::<TrustMode>(SCHEMA_FILENAMES[50])?,
        schema_document::<WireValue>(SCHEMA_FILENAMES[51])?,
    ])
}

fn schema_document<T: JsonSchema>(filename: &'static str) -> Result<(&'static str, Vec<u8>)> {
    let mut document = serde_json::to_value(schema_for!(T))?;
    normalize_schema_meta(&mut document, filename)?;
    let mut bytes = serde_json::to_vec_pretty(&document)?;
    bytes.push(b'\n');
    Ok((filename, bytes))
}

fn normalize_schema_meta(document: &mut Value, filename: &str) -> Result<()> {
    if let Value::Object(object) = document {
        object.insert(
            "$schema".to_owned(),
            Value::String("https://json-schema.org/draft/2020-12/schema".to_owned()),
        );
    }
    add_explicit_integer_bounds(document);
    if filename == "certification-evidence.schema.json" {
        annotate_certification_evidence(document)?;
    }
    if filename == "certification-profile.schema.json" {
        annotate_certification_profile(document)?;
    }
    if filename == "certification-runner-component-descriptor.schema.json" {
        annotate_certification_runner_component(document)?;
    }
    if filename == "certification-runner-identity.schema.json"
        && let Value::Object(root) = document
    {
        root.insert(
            "x-weregopher-maxDocumentBytes".to_owned(),
            json!(weregopher_domain::MAX_CERTIFICATION_RUNNER_IDENTITY_DOCUMENT_BYTES),
        );
    }
    if filename == "compatibility-analysis.schema.json" {
        require_evidence_for_resolved_compatibility_assessments(document)?;
    }
    if filename == "disposable-certification-scenario.schema.json" {
        annotate_disposable_certification_scenario(document)?;
    }
    if filename == "disposable-certification-scenario-report.schema.json"
        && let Value::Object(root) = document
    {
        root.insert(
            "x-weregopher-maxDocumentBytes".to_owned(),
            json!(weregopher_domain::MAX_DISPOSABLE_CERTIFICATION_SCENARIO_REPORT_BYTES),
        );
    }
    if filename == "discord-smoke-certification-report.schema.json"
        && let Value::Object(root) = document
    {
        root.insert(
            "x-weregopher-maxDocumentBytes".to_owned(),
            json!(weregopher_adapter_discord::MAX_DISCORD_SMOKE_CERTIFICATION_REPORT_BYTES),
        );
    }
    if matches!(
        filename,
        "local-certification-ledger-record.schema.json"
            | "local-certification-run-attestation.schema.json"
    ) {
        annotate_local_certification_attestation_constraints(document)?;
    }
    if filename == "local-certification-ledger-record.schema.json" {
        annotate_local_certification_ledger(document)?;
    }
    if filename == "local-certification-run-attestation.schema.json" {
        let root = document
            .as_object_mut()
            .context("local certification attestation schema root is not an object")?;
        root.insert(
            "x-weregopher-maxDocumentBytes".to_owned(),
            json!(weregopher_domain::MAX_LOCAL_CERTIFICATION_RUN_ATTESTATION_BYTES),
        );
    }
    if filename == "renderer-bridge-reply.schema.json" {
        require_exactly_one_renderer_bridge_reply_outcome(document)?;
    }
    if filename == "g2-feasibility-report.schema.json" {
        require_g2_gate_evidence_status_binding(document)?;
    }
    if filename == "openai-package-inventory.schema.json" {
        annotate_openai_package_inventory(document)?;
    }
    if matches!(
        filename,
        "renderer-bridge-invocation.schema.json" | "renderer-envelope.schema.json"
    ) {
        reject_zero_renderer_bridge_nonce(document)?;
    }
    match filename {
        "execution-target-contract.schema.json" => annotate_execution_target_limits(document)?,
        "execution-resolution-evidence.schema.json" => {
            annotate_execution_resolution_limits(document)?;
        }
        _ => {}
    }
    Ok(())
}

fn require_g2_gate_evidence_status_binding(document: &mut Value) -> Result<()> {
    let gate = document
        .pointer_mut("/$defs/G2GateEvidence")
        .and_then(Value::as_object_mut)
        .context("G2 gate evidence schema definition is missing")?;
    gate.insert(
        "oneOf".to_owned(),
        json!([
            {
                "properties": {
                    "status": {"const": "not_run"},
                    "evidence_digest": {"type": "null"}
                },
                "required": ["status"]
            },
            {
                "properties": {
                    "status": {"enum": ["failed", "passed"]},
                    "evidence_digest": {"$ref": "#/$defs/Sha256Digest"}
                },
                "required": ["status", "evidence_digest"]
            }
        ]),
    );
    Ok(())
}

fn annotate_openai_package_inventory(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("OpenAI package inventory schema root is not an object")?;
    root.insert(
        "x-weregopher-uniqueComponentLocation".to_owned(),
        json!(["source", "path"]),
    );
    let definitions = root
        .get_mut("$defs")
        .and_then(Value::as_object_mut)
        .context("OpenAI package inventory schema definitions are missing")?;
    let package_path = definitions
        .get_mut("G2PackagePath")
        .and_then(Value::as_object_mut)
        .context("G2 package path schema definition is missing")?;
    package_path.insert(
        "pattern".to_owned(),
        json!(r"^(?!/)(?!.*(?:^|/)(?:\.|\.\.)(?:/|$))(?!.*//)(?!.*\\)(?!.*\/$)[^\u0000-\u001f]+$"),
    );
    package_path.insert(
        "x-weregopher-maxComponents".to_owned(),
        json!(weregopher_domain::MAX_G2_PACKAGE_PATH_COMPONENTS),
    );
    let byte_length = definitions
        .get_mut("G2ComponentEvidence")
        .and_then(Value::as_object_mut)
        .and_then(|component| component.get_mut("properties"))
        .and_then(Value::as_object_mut)
        .and_then(|properties| properties.get_mut("byte_length"))
        .and_then(Value::as_object_mut)
        .context("G2 component byte-length schema is missing")?;
    byte_length.insert("minimum".to_owned(), json!(1));
    Ok(())
}

fn require_exactly_one_renderer_bridge_reply_outcome(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("renderer bridge reply schema root is not an object")?;
    root.insert(
        "oneOf".to_owned(),
        json!([
            {
                "required": ["result"],
                "properties": {
                    "result": {
                        "not": {
                            "type": "null"
                        }
                    },
                    "error": {
                        "type": "null"
                    }
                }
            },
            {
                "required": ["error"],
                "properties": {
                    "result": {
                        "type": "null"
                    },
                    "error": {
                        "not": {
                            "type": "null"
                        }
                    }
                }
            }
        ]),
    );
    Ok(())
}

fn reject_zero_renderer_bridge_nonce(document: &mut Value) -> Result<()> {
    let nonce = document
        .pointer_mut("/$defs/RendererBridgeNonce")
        .and_then(Value::as_object_mut)
        .context("renderer bridge schema is missing its nonce definition")?;
    nonce.insert(
        "not".to_owned(),
        json!({
            "const": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        }),
    );
    Ok(())
}

fn annotate_disposable_certification_scenario(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("disposable certification scenario schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_DISPOSABLE_CERTIFICATION_SCENARIO_BYTES),
    );

    let execution = document
        .pointer_mut("/$defs/DisposableScenarioExecution/properties")
        .and_then(Value::as_object_mut)
        .context("disposable certification scenario schema is missing execution properties")?;
    execution.insert(
        "state_mode".to_owned(),
        json!({
            "const": "disposable",
            "type": "string"
        }),
    );
    execution.insert(
        "security_posture".to_owned(),
        json!({
            "const": "vendor_equivalent_full_trust",
            "type": "string"
        }),
    );
    execution.insert(
        "dependency_policy".to_owned(),
        json!({
            "const": "vendor_default_ambient",
            "type": "string"
        }),
    );

    let state_roots = document
        .pointer_mut("/properties/state_roots")
        .and_then(Value::as_object_mut)
        .context("disposable certification scenario schema is missing state roots")?;
    state_roots.insert(
        "contains".to_owned(),
        json!({
            "type": "object",
            "required": ["definition"],
            "properties": {
                "definition": {
                    "type": "object",
                    "required": ["kind"],
                    "properties": {
                        "kind": {
                            "const": "success_file"
                        }
                    }
                }
            }
        }),
    );
    state_roots.insert("minContains".to_owned(), json!(1));
    state_roots.insert("maxContains".to_owned(), json!(1));
    Ok(())
}

fn annotate_certification_evidence(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("certification evidence schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_DOCUMENT_BYTES),
    );
    let assessment = document
        .pointer_mut("/$defs/CertificationCheckAssessment")
        .and_then(Value::as_object_mut)
        .context("certification schema is missing its check-assessment definition")?;
    assessment.insert(
        "allOf".to_owned(),
        json!([{
            "if": {
                "properties": {
                    "status": { "const": "not_run" }
                },
                "required": ["status"]
            },
            "then": {
                "properties": {
                    "evidence": { "maxItems": 0 }
                }
            },
            "else": {
                "properties": {
                    "evidence": { "minItems": 1 }
                }
            }
        }]),
    );
    Ok(())
}

fn annotate_certification_profile(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("certification profile schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_PROFILE_DOCUMENT_BYTES),
    );
    Ok(())
}

fn annotate_certification_runner_component(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("certification runner component schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_RUNNER_COMPONENT_DESCRIPTOR_BYTES),
    );
    root.insert(
        "x-weregopher-maxAggregateArtifactNameBytes".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_RUNNER_COMPONENT_ARTIFACT_NAME_BYTES),
    );

    for definition in [
        "CertificationRunnerArtifactName",
        "CertificationRunnerComponentId",
        "CertificationRunnerComponentVersion",
    ] {
        let text = document
            .pointer_mut(&format!("/$defs/{definition}"))
            .and_then(Value::as_object_mut)
            .with_context(|| {
                format!(
                    "certification runner component schema is missing its {definition} definition"
                )
            })?;
        text.insert("minLength".to_owned(), json!(1));
        text.insert(
            "maxLength".to_owned(),
            json!(weregopher_domain::MAX_CERTIFICATION_RUNNER_COMPONENT_TEXT_BYTES),
        );
        text.insert(
            "x-weregopher-maxUtf8Bytes".to_owned(),
            json!(weregopher_domain::MAX_CERTIFICATION_RUNNER_COMPONENT_TEXT_BYTES),
        );
        text.insert(
            "pattern".to_owned(),
            Value::String(
                r"^(?!/)(?!.*\/$)(?!.*//)(?!.*(?:^|/)\.{1,2}(?:/|$))(?!.*\\)(?!.*\p{Cc})(?!.*[. ](?:/|$)).+$"
                    .to_owned(),
            ),
        );
    }

    let artifact_size = document
        .pointer_mut("/$defs/CertificationRunnerComponentArtifact/properties/size_bytes")
        .and_then(Value::as_object_mut)
        .context("certification runner component schema is missing its artifact size definition")?;
    artifact_size.insert("minimum".to_owned(), json!(1));
    artifact_size.insert(
        "maximum".to_owned(),
        json!(weregopher_domain::MAX_CERTIFICATION_RUNNER_COMPONENT_ARTIFACT_BYTES),
    );
    Ok(())
}

fn annotate_local_certification_attestation_constraints(document: &mut Value) -> Result<()> {
    let freshness = document
        .pointer_mut("/$defs/CertificationRunFreshness/properties")
        .and_then(Value::as_object_mut)
        .context("local certification schema is missing its freshness properties")?;
    let maximum_elapsed = freshness
        .get_mut("maximum_elapsed_millis")
        .and_then(Value::as_object_mut)
        .context("local certification schema is missing its freshness limit")?;
    maximum_elapsed.insert("minimum".to_owned(), json!(1));
    maximum_elapsed.insert(
        "maximum".to_owned(),
        json!(weregopher_domain::MAX_LOCAL_CERTIFICATION_RUN_FRESHNESS_MILLIS),
    );
    let elapsed = freshness
        .get_mut("elapsed_millis")
        .and_then(Value::as_object_mut)
        .context("local certification schema is missing its elapsed duration")?;
    elapsed.insert(
        "maximum".to_owned(),
        json!(weregopher_domain::MAX_LOCAL_CERTIFICATION_RUN_FRESHNESS_MILLIS),
    );
    elapsed.insert(
        "x-weregopher-maximumField".to_owned(),
        Value::String("maximum_elapsed_millis".to_owned()),
    );

    set_schema_minimum(
        document,
        "/$defs/CertificationRunRunnerIdentity/properties/policy_generation",
        1,
        "runner policy generation",
    )?;
    set_schema_minimum(
        document,
        "/$defs/CertificationRunResultIdentity/properties/policy_generation",
        1,
        "certification policy generation",
    )?;
    set_schema_minimum(
        document,
        "/$defs/CertificationRunResultIdentity/properties/artifact_count",
        1,
        "certification artifact count",
    )?;
    set_schema_minimum(
        document,
        "/$defs/CertificationRunResultIdentity/properties/total_artifact_bytes",
        1,
        "certification aggregate artifact bytes",
    )?;
    set_assignable_certification_classes(
        document,
        "/$defs/CertificationRunResultIdentity/properties/class",
        "certification result class",
    )?;
    Ok(())
}

fn annotate_local_certification_ledger(document: &mut Value) -> Result<()> {
    set_schema_minimum(
        document,
        "/properties/sequence",
        1,
        "local certification ledger sequence",
    )?;
    set_schema_minimum(
        document,
        "/$defs/CertificationControlPolicy/properties/policy_generation",
        1,
        "local certification control-policy generation",
    )?;
    set_assignable_certification_classes(
        document,
        "/$defs/CertificationControlPolicy/properties/class",
        "local certification control-policy class",
    )?;
    let publication_status = document
        .pointer_mut("/$defs/LocalCertificationLedgerReceipt/properties/publication_status")
        .and_then(Value::as_object_mut)
        .context("local certification ledger schema is missing its receipt publication status")?;
    publication_status.insert("const".to_owned(), Value::String("local_only".to_owned()));

    let root = document
        .as_object_mut()
        .context("local certification ledger schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_LOCAL_CERTIFICATION_LEDGER_RECORD_BYTES),
    );
    let required = root
        .get_mut("required")
        .and_then(Value::as_array_mut)
        .context("local certification ledger schema is missing its required fields")?;
    let previous = Value::String("previous_record_digest".to_owned());
    if !required.contains(&previous) {
        required.push(previous);
    }
    root.insert(
        "allOf".to_owned(),
        json!([{
            "if": {
                "properties": {
                    "sequence": { "const": 1 }
                },
                "required": ["sequence"]
            },
            "then": {
                "properties": {
                    "previous_record_digest": { "type": "null" },
                    "event": {
                        "properties": {
                            "kind": { "const": "genesis" }
                        },
                        "required": ["kind"]
                    }
                }
            },
            "else": {
                "properties": {
                    "sequence": { "minimum": 2 },
                    "previous_record_digest": {
                        "$ref": "#/$defs/LocalCertificationLedgerRecordDigest"
                    },
                    "event": {
                        "not": {
                            "properties": {
                                "kind": { "const": "genesis" }
                            },
                            "required": ["kind"]
                        }
                    }
                }
            }
        }]),
    );
    Ok(())
}

fn set_schema_minimum(
    document: &mut Value,
    pointer: &str,
    minimum: u64,
    description: &str,
) -> Result<()> {
    let property = document
        .pointer_mut(pointer)
        .and_then(Value::as_object_mut)
        .with_context(|| format!("local certification schema is missing its {description}"))?;
    property.insert("minimum".to_owned(), json!(minimum));
    Ok(())
}

fn set_assignable_certification_classes(
    document: &mut Value,
    pointer: &str,
    description: &str,
) -> Result<()> {
    let property = document
        .pointer_mut(pointer)
        .and_then(Value::as_object_mut)
        .with_context(|| format!("local certification schema is missing its {description}"))?;
    property.insert(
        "enum".to_owned(),
        json!([
            "structural_verified",
            "smoke_verified",
            "contract_verified",
            "exact_certified"
        ]),
    );
    Ok(())
}

fn annotate_execution_target_limits(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("execution target schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_EXECUTION_TARGET_DOCUMENT_BYTES),
    );
    let arguments = document
        .pointer_mut("/$defs/ExecutionLaunchPolicy/properties/arguments")
        .and_then(Value::as_object_mut)
        .context("execution target schema is missing launch arguments")?;
    arguments.insert(
        "x-weregopher-maxAggregateUtf8Bytes".to_owned(),
        json!(weregopher_domain::MAX_EXECUTION_ARGUMENT_AGGREGATE_BYTES),
    );
    Ok(())
}

fn annotate_execution_resolution_limits(document: &mut Value) -> Result<()> {
    let root = document
        .as_object_mut()
        .context("execution resolution schema root is not an object")?;
    root.insert(
        "x-weregopher-maxDocumentBytes".to_owned(),
        json!(weregopher_domain::MAX_EXECUTION_RESOLUTION_DOCUMENT_BYTES),
    );
    root.insert(
        "x-weregopher-managedLocatorDigestEqualsExecutableDigest".to_owned(),
        Value::Bool(true),
    );
    Ok(())
}

fn require_evidence_for_resolved_compatibility_assessments(document: &mut Value) -> Result<()> {
    let assessment = document
        .pointer_mut("/$defs/DimensionAssessment")
        .and_then(Value::as_object_mut)
        .context("compatibility schema is missing its dimension-assessment definition")?;
    assessment.insert(
        "allOf".to_owned(),
        json!([{
            "if": {
                "properties": {
                    "status": {
                        "enum": ["satisfied", "unsatisfied", "not_applicable"]
                    }
                },
                "required": ["status"]
            },
            "then": {
                "properties": {
                    "evidence": {
                        "minItems": 1
                    }
                }
            }
        }]),
    );
    Ok(())
}

fn add_explicit_integer_bounds(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let format = object
                .get("format")
                .and_then(Value::as_str)
                .map(str::to_owned);
            if let Some((minimum, maximum)) = format.as_deref().and_then(integer_bounds) {
                object.entry("minimum").or_insert(minimum);
                object.entry("maximum").or_insert(maximum);
            }
            for child in object.values_mut() {
                add_explicit_integer_bounds(child);
            }
        }
        Value::Array(values) => {
            for child in values {
                add_explicit_integer_bounds(child);
            }
        }
        _ => {}
    }
}

fn integer_bounds(format: &str) -> Option<(Value, Value)> {
    match format {
        "uint8" => Some((Value::from(0), Value::from(u8::MAX))),
        "uint16" => Some((Value::from(0), Value::from(u16::MAX))),
        "uint32" => Some((Value::from(0), Value::from(u32::MAX))),
        "uint64" => Some((Value::from(0), Value::from(u64::MAX))),
        "int8" => Some((Value::from(i8::MIN), Value::from(i8::MAX))),
        "int16" => Some((Value::from(i16::MIN), Value::from(i16::MAX))),
        "int32" => Some((Value::from(i32::MIN), Value::from(i32::MAX))),
        "int64" => Some((Value::from(i64::MIN), Value::from(i64::MAX))),
        _ => None,
    }
}
